### ISSUE TITLE
"Install Redis packages" task fails when run on CentOS 9 Stream system

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/metrics#114]
When running the Metrics role against a CentOS Stream 9 system, the "Install Redis packages" task fails with error:

fatal: [c9s-server1.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '__redis_packages_extra' is undefined\n\nThe error appears to be in '/usr/share/linux-system-roles/metrics/roles/redis/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Redis packages\n  ^ here\n"}

This is probably related to there being no metrics/roles/redis/vars/CentOS_9.yml file to define this variable.

Here are the ansible_distribution variables gathered from my CentOS 9 Stream system:

        "ansible_distribution": "CentOS",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/redhat-release",
        "ansible_distribution_file_variety": "RedHat",
        "ansible_distribution_major_version": "9",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "9",

**Comment by natoscott** [comment]
Thanks @briansmith0 - fix incoming shortly via the automated `ansible-pcp` sync.

**Comment by natoscott** [comment]
Was fixed some time back, and now verified via CI on rhel9 that is now passing.
