### ISSUE TITLE
"Ensure performance metric collector authentication is configured" task fails when run on CentOS 9 Stream system

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/metrics#115]
When running the Metrics role against a CentOS Stream 9 system, the "Ensure performance metric collector authentication is configured" task fails with error:

fatal: [c9s-server1.example.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: '__pcp_sasl_mechlist' is undefined"}

This is probably related to there being no metrics/roles/pcp/vars/CentOS_9.yml file to define this variable.

Here are the ansible_distribution variables gathered from my CentOS 9 Stream system:

    "ansible_distribution": "CentOS",
    "ansible_distribution_file_parsed": true,
    "ansible_distribution_file_path": "/etc/redhat-release",
    "ansible_distribution_file_variety": "RedHat",
    "ansible_distribution_major_version": "9",
    "ansible_distribution_release": "NA",
    "ansible_distribution_version": "9",

**Comment by natoscott** [comment]
Thanks @briansmith0 - fix incoming shortly via the automated `ansible-pcp` sync.

**Comment by kwozyman** [comment]
This is also the case with Rocky Linux 9.1

**Comment by natoscott** [comment]
Was fixed some time back, and now verified via CI on rhel9 that is now passing.
