### ISSUE TITLE
Graph access ideas

### ISSUE THREAD

**Issue by myllynen** [linux-system-roles/metrics#25]
I tried this role on RHEL 8.3 and it works well, however few items could be improved for graph access:

* Grafana port or URL is not mentioned anywhere in the README, while it may be obvious for many it would still be helpful to spell it out in the README
* Ideally there would be an option to setup all components to listen to localhost ports only so making services accessible from outside would be opt-in (or at least possible to opt-out), now the services are exposed to the world after executing the role
* It could be explained - or perhaps even automated - how to open the needed firewall ports for remote access
* Accessing graphs over HTTPS doesn't seem to work, I get Error code: SSL_ERROR_RX_RECORD_TOO_LONG (using a self-signed certificate would not be perfect but at least it would allow using HTTPS, now there is no way around this error)

Thanks.

**Comment by richm** [comment]
> I tried this role on RHEL 8.3 and it works well, however few items could be improved for graph access:
> 
>     * Grafana port or URL is not mentioned anywhere in the README, while it may be obvious for many it would still be helpful to spell it out in the README
> 
>     * Ideally there would be an option to setup all components to listen to localhost ports only so making services accessible from outside would be opt-in (or at least possible to opt-out), now the services are exposed to the world after executing the role
> 
>     * It could be explained - or perhaps even automated - how to open the needed firewall ports for remote access

Should definitely be in the README - also any selinux considerations.  This is what we have done in other system roles - documented the firewall and selinux considerations in the README - it is the responsibility of the user to ensure firewall and selinux are set up appropriately - we will probably in the future have system roles use other system roles to set these things up e.g. have the metrics role use the firewall role to set up firewall, the selinux role to apply custom policy, and the certificate role to issue server certs for https.
 
>     * Accessing graphs over HTTPS doesn't seem to work, I get Error code: SSL_ERROR_RX_RECORD_TOO_LONG (using a self-signed certificate would not be perfect but at least it would allow using HTTPS, now there is no way around this error)

Does the metrics role need to allow the user to provide a cacert, server cert, server key?

> 
> 
> Thanks.

**Comment by natoscott** [comment]
I'll add some notes to the README about each of the ports (pmcd, pmproxy, redis-server and grafana-server each have one).

> Does the metrics role need to allow the user to provide a cacert, server cert, server key?

The current metrics role doesn't attempt to set up certificates, as it doesn't enable any encrypted access today (was not on the shopping list from PM) - I expect for a future version this will be needed - each of the above servers can be configured for TLS.

**Comment by richm** [comment]
The current role has support for firewall and selinux. I think we can close this.
