### ISSUE TITLE
The role uses wrong role name when pointing to it self

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#33]
In the metrics role there are the following tasks pointing to the role it self:

- roles/performancecopilot_metrics_bpftrace/tasks/main.yml
- roles/performancecopilot_metrics_elasticsearch/tasks/main.yml
- roles/performancecopilot_metrics_mssql/tasks/main.yml

However it points to it self as `pcp` role, while the role it self is called `performancecopilot_metrics_pcp`.

Any playbook enabling bptftrace or elasticsearch or mssql fails on this issue. Renaming the role from  `pcp` to `performancecopilot_metrics_pcp` in those three tasks above fix the issue.

**Comment by kurik** [comment]
Proposed fix: https://github.com/linux-system-roles/metrics/pull/40

**Comment by natoscott** [comment]
Ugh, this is fallout from using different names for the embedded roles to those used in ansible-pcp  :(
Need to think about the best approach here a bit, may be better to revert the names to make them match (but that has other downsides), or to finally bite the bullet and ship ansible-pcp roles properly (i.e. separately, not embedded in the metrics role).

**Comment by natoscott** [comment]
I've updated these to use performancecopilot_metrics_pcp for now, which should be the right interim fix until ansible-pcp arrives as a standalone package / collection.

**Comment by natoscott** [comment]
This is not yet correct, as per notes in #40
