### ISSUE TITLE
MSSQL agent does not register it self in PMCD due to missing python3-pyodbc package

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#36]
When `metrics_from_mssql: yes` is set in a playbook, the role installs MSSQL agent. However registration of this agent in PMCD fails due to missing `python3-pyodbc` package.

The fail of the registration is not recognized by the playbook run. The run of such playbook succeeds, but the MSSQL agent simply does not work due to the missing registration.

_Note: This has been tested on Fedora-33 and RHEL-8.4-Development distros. As I do not have Debian or other distros available, I can not confirm this issue on those other distros._

**Comment by natoscott** [comment]
@kurik I think this is fixed in more recent versions of PCP, as best we can.  On f33 were you using a PCP version predating pcp-5.2.3?  An rpm dependency was added there...

```$ rpm -qR pcp-pmda-mssql | grep pyodbc
python3-pyodbc
```

In RHEL8, we await this (new) package - still expected in 8.4 via BZ #1881490 AIUI - until then, there's little we can do here.

**Comment by kurik** [comment]
Hmm, I guess I was using pcp-5.2.3 on F33, but honestly I am not 100% sure now. However when I check it now, it works as expected.

For RHEL - the `python3-odbc` package is already available in devel composes of 8.4, so we might add the dependency here as well. Without  the `python3-odbc` package installed, we can not do any automated tests of the `metrics_from_mssql: yes` functionality on RHEL, because the PMDA is not installable. If adding the dependency will be an issue for 8.4, we might postpone it to 8.5.

**Comment by natoscott** [comment]
Thanks Jan - closing as discussed (and on IRC) - the 8.4 pcp build will have this dep.
