### ISSUE TITLE
rhel8.conf 

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/metrics#6]
Hi,
You added in your initial patch a rhel8.conf

```
[options]
version = 1

[rhel8-zeroconf]
interval = 1s
#proc metrics
proc.psinfo.cmd = ,
proc.psinfo.sname = ,
proc.psinfo.ppid = ,
```

What is it used for?
Is it required when installing pcp-zeroconf?

@lberk

**Comment by lberk** [comment]
That seems like a leftover from a previous approach I had but failed to cull before sending to you.  Sorry about that, feel free to drop for now.
