### ISSUE TITLE
Configuration of bpftrace PMDA does not work on platforms where PCP version is less or equal to 5.1 

### ISSUE THREAD

**Issue by kurik** [linux-system-roles/metrics#63]
**Background**
bpftrace agent is delivered to a system via `pcp-pmda-bpftrace` package. Starting from PCP version 5.2 the `pcp-pmda-bpftrace` package has changed the layout of files on a filesystem. While in PCP <= 5.1 the PMDA files are located in `/var/lib/pcp/pmdas/bpftrace` directory, in PCP >= 5.2 the files are located in `/usr/libexec/pcp/pmdas/bpftrace` and `bpftrace.conf` is located in `/etc/pcp/bpftrace/` directory. For PCP >= 5.2 there are symlinks from the old  `/var/lib/pcp/pmdas/bpftrace` directory to new locations, to achieve backward compatibility.

**The issue**
When `metrics_from_bpftrace: yes` is set in a playbook, the role generates the `bpftrace.conf` file in `/etc/pcp/bpftrace/` directory (so it supports PCP >= 5.2). However when the role runs on a platform with PCP <= 5.1, than the config file is expected by the PMDA to be in `/var/lib/pcp/pmdas/bpftrace` directory. As such, all the platforms with PCP <= 5.1 do not have bpftrace agent configured properly (a default config file is used instead).

 List of affected platforms:
* RHEL <= 8.3
* CentOS - all currently available releases

The same issue affects also configuration files of `mssql` and `elasticsearch` PMDAs.

**Comment by natoscott** [comment]
@kurik right you are - I'll update these paths to use the original paths (now symlinks) instead for better compatibility.  For Fedora and RHEL9 onward we can switch to the /etc paths.
