### ISSUE TITLE
Update fields names collected from the openmetrics endpoint

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/metrics#8]
I need to update the fields names you mentioned in issue #3, and add additional metadata.
In Elasticsearch we send json documents.

This is an example of how it should look like when we send to Elasticsearch.
```
{
	"time": "2017-01-19T:29:10+00:00",
	"collectd.processes.ps_code": 21635072,
	"dstypes": "gauge",
	"interval": 10.0,
	"host": "dhcp-0-135.tlv.redhat.com",
	"plugin": "processes",
	"plugin_instance": "collectd",
	"type": "ps_code",
	"type_instance": "",
	"ovirt": {
		"entity": "host",
		"host_id": "{{ ovirt_vds_vds_id }}",
		"engine_fqdn": "{{ ovirt_engine_fqdn }}",
		"cluster_name": "{{ ovirt_vds_cluster_name }}"
	},
	"tag": "project.ovirt-metrics-{{ ovirt_env_name }}",
	"hostname": "hostname",
	"ipaddr4": "ip address"
}
```

Under "ovirt" are additional metadata.  
@lberk

**Comment by lberk** [comment]
Looking at the json document, which bits of metadata were you specifically interested in?

'host/hostname' seems to be repeated 3 times?

'plugin', 'plugin_instance', 'type', 'type_instance' seem to be collectd specific?  Do we need those? Interval doesn't have any units attached to it (I assume it's in seconds, but would we want that as well?)
ipaddr4: are we only looking at ipv4? no ipv6? what happens if the box has more than one ip address?

**Comment by sradco** [comment]
> Looking at the json document, which bits of metadata were you specifically interested in?
> 
> 'host/hostname' seems to be repeated 3 times?
"host": "dhcp-0-135.tlv.redhat.com"
But its only and example.
> 
> 'plugin', 'plugin_instance', 'type', 'type_instance' seem to be collectd specific? Do we need those? 
Yes. The are used in Kibana for filtering the data. I would like to be backwards compatible if it is possible.

Interval doesn't have any units attached to it (I assume it's in seconds, but would we want that as well?)
Seconds
> ipaddr4: are we only looking at ipv4? no ipv6? what happens if the box has more than one ip address?
Only ipv4

It is more of a general question how we can add metadata and update the "value" field names to be in this format: "collectd.processes.ps_code".
Adding Metadata is mandatory for out use case.
The renaming is for backwards compatibility, but I'm still checking if we must be backward compatible.
@lberk

**Comment by lberk** [comment]
>> 'plugin', 'plugin_instance', 'type', 'type_instance' seem to be collectd specific? Do we need those?

>Yes. The are used in Kibana for filtering the data. I would like to be backwards compatible if it is possible.

Ok, for the plugin, and plugin_intance I'm not seeing that exported anywhere in my local setup.  How were you envisioning that data being exported for us to pick up?

As for metadata in a general case, PCP has the concept of 'labels' that would be a good fit here, I'm working on extending some of that through the python libraries now (so it can be used via pcp2elasticsearch) and we can specify them via ansible config files as needed.
