### ISSUE TITLE
Is restart of PCP required after installing of additional packages?

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/metrics#9]
Is restart of PCP required after installing of additional packages?
@lberk

**Comment by natoscott** [comment]
@sradco which packages in particular?  the PCP packages will restart daemons like pmcd as needed, so unless there is something special being done by a particular package, typically no restart is required.

**Comment by natoscott** [comment]
The new version of the metrics role uses performancecopilot.pcp role, which restarts daemons as needed.
